/* UI shell over the existing PDOK/Leaflet, MapLibre and spatial-search adapters.
   No concept images or invented site records are used by the live interface. */
(() => {
  const $=id=>document.getElementById(id);
  const messages={
    'Criterion':['Criterium','Kriterium'],'Designation':['Bestemming','Festsetzung'],'Municipality':['Gemeente','Gemeinde'],'Cadastral parcel':['Kadastraal perceel','Flurstück'],'Plan status':['Planstatus','Planstatus'],'Plan date':['Plandatum','Plandatum'],'Heritage / dual':['Erfgoed / dubbel','Denkmal / Zusatz'],'Dimensions':['Maatvoering','Maßangaben'],'Station · approx.':['Station · indicatief','Bahnhof · ungefähr'],'Park · approx.':['Park · indicatief','Park · ungefähr'],'Industry · approx.':['Industrie · indicatief','Industrie · ungefähr'],'Source':['Bron','Quelle'],'Evidence captured':['Gegevens vastgelegd','Daten erfasst'],'Review':['Beoordeling','Prüfung'],'Partial evidence':['Onvolledige gegevens','Unvollständige Daten'],'Current legal position must be checked.':['Controleer de actuele juridische situatie.','Aktuelle Rechtslage prüfen.'],
    Explore:['Verkennen','Erkunden'],Inspect:['Inspecteren','Prüfen'],Compare:['Vergelijken','Vergleichen'],Cases:['Dossiers','Fälle'],Search:['Zoeken','Suche'],Saved:['Bewaard','Gespeichert'],
    Day:['Dag','Tag'],Night:['Nacht','Nacht'],Sand:['Zand','Sand'],System:['Systeem','System'],Appearance:['Weergave','Darstellung'],Layers:['Lagen','Ebenen'],Planning:['Plannen','Planung'],Context:['Omgeving','Umgebung'],
    Summary:['Overzicht','Übersicht'],Rules:['Regels','Regeln'],Sources:['Bronnen','Quellen'],'Add to comparison':['Vergelijken','Zum Vergleich'],'Export brief':['Exporteer dossier','Bericht exportieren'],
    'Visible':['Zichtbaar','Sichtbar'],'Zoom to detail':['Zoom naar detail','Details vergrößern'],'Visible closer in':['Zichtbaar na inzoomen','Beim Hineinzoomen sichtbar'],'Off':['Uit','Aus'],'Loading…':['Laden…','Lädt…'],'Some tiles unavailable':['Sommige tegels ontbreken','Einige Kacheln fehlen'],
    'Draw area':['Gebied tekenen','Bereich markieren'],'Measure':['Meten','Messen'],'Stop measuring':['Stop meten','Messung beenden'],'Close':['Sluiten','Schließen'],
    'Expand details':['Details vergroten','Details vergrößern'],'Collapse details':['Details verkleinen','Details verkleinern'],
    'Street View':['Street View','Street View'],'Aerial context · Esri':['Luchtfoto · Esri','Luftbild · Esri'],'Street imagery opens externally':['Straatbeeld opent extern','Straßenansicht öffnet extern'],
    'Your next site starts here.':['Je volgende locatie begint hier.','Hier beginnt deine Standortsuche.'],
    'Explore adjoining plans, then click a location to inspect its source.':['Bekijk aangrenzende plannen en klik op een locatie voor de bron.','Benachbarte Pläne ansehen und einen Standort samt Quelle prüfen.'],
    'Explore Maastricht':['Verken Maastricht','Maastricht erkunden'],'Find an area':['Zoek een gebied','Gebiet finden'],
    'Compare sites':['Locaties vergelijken','Standorte vergleichen'],'Saved cases':['Bewaarde dossiers','Gespeicherte Fälle'],'Back to map':['Terug naar kaart','Zur Karte'],
    'Choose up to three sites.':['Kies maximaal drie locaties.','Bis zu drei Standorte auswählen.'],'Compare real plan evidence side by side.':['Vergelijk echte plangegevens naast elkaar.','Echte Plandaten direkt vergleichen.'],
    'No sites compared yet':['Nog geen vergelijking','Noch keine Standorte im Vergleich'],'Select an area, then add it to your comparison.':['Selecteer een gebied en voeg het toe aan de vergelijking.','Eine Fläche auswählen und zum Vergleich hinzufügen.'],
    'No saved cases yet':['Nog geen dossiers','Noch keine Fälle gespeichert'],'Save a selected location to keep its evidence and your notes on this device.':['Bewaar een locatie met gegevens en notities op dit apparaat.','Einen Standort mit Belegen und Notizen auf diesem Gerät speichern.'],
    'Open on map':['Open op kaart','Auf Karte öffnen'],'Remove':['Verwijderen','Entfernen'],'Notes and open questions':['Notities en open vragen','Notizen und offene Fragen'],
    'Stored on this device. Sources are snapshots; reopen a site to refresh.':['Opgeslagen op dit apparaat. Open een locatie opnieuw voor actuele gegevens.','Lokal gespeichert. Standort erneut öffnen, um aktuelle Daten zu laden.'],
    'No evidence snapshot yet':['Nog geen gegevensmomentopname','Noch kein Datenstand gespeichert'],'Not queried':['Niet opgevraagd','Nicht abgefragt'],'Not returned':['Niet gevonden','Nicht zurückgegeben'],'Unknown':['Onbekend','Unbekannt'],'Mapped':['Ingetekend','Kartiert'],'Needs review':['Te controleren','Zu prüfen'],
    'Matches':['Treffers','Treffer'],'All':['Alle','Alle'],'Add':['Toevoegen','Hinzufügen'],'Cancel':['Annuleren','Abbrechen'],
    'Search cancelled. Displayed results are partial.':['Zoeken geannuleerd. Getoonde resultaten zijn onvolledig.','Suche abgebrochen. Angezeigte Ergebnisse sind unvollständig.'],
    'Query failed for some sources.':['Enkele bronvragen zijn mislukt.','Einige Quellenabfragen sind fehlgeschlagen.'],
    'Source linked · legal review required':['Bron gekoppeld · juridische toets nodig','Quelle verknüpft · rechtliche Prüfung nötig'],
    'Manual criteria':['Handmatige criteria','Manuelle Kriterien'],'Zoning group':['Bestemmingsgroep','Nutzungsgruppe'],'Any designation':['Elke bestemming','Alle Nutzungen'],Residential:['Wonen','Wohnen'],'Mixed use':['Gemengd','Mischnutzung'],
    'Building envelope':['Bouwvlak','Baufenster'],'No mapped building':['Geen gebouw op punt','Kein Gebäude am Punkt'],'Near station (km)':['Nabij station (km)','Bahnhofnähe (km)'],'Near park (km)':['Nabij park (km)','Parknähe (km)'],'Industry distance (km)':['Industrieafstand (km)','Industrieabstand (km)'],'Run manual search':['Handmatig zoeken','Manuell suchen'],'Blank distance = no filter. Straight-line approximations.':['Leeg = geen filter. Afstanden bij benadering in rechte lijn.','Leer = kein Filter. Ungefähre Luftlinienabstände.']
  };
  const t=s=>messages[s]?.[document.documentElement.lang==='nl'?0:document.documentElement.lang==='de'?1:-1]||s;
  const ui={view:'explore',tab:'summary',compare:[],layerStatus:{},measuring:false,measurePoints:[],ready:false,appearance:'day',streetClosed:false};
  const button=(label,id='',cls='pv-button')=>`<button type="button" ${id?`id="${id}"`:''} class="${cls}">${esc(t(label))}</button>`;
  function readStorage(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
  function writeStorage(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{showToast('Local storage is unavailable. Export your brief to keep it.');return false;}}
  function applyAppearance(choice){ui.appearance=['day','night','sand','system'].includes(choice)?choice:'day';const resolved=ui.appearance==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'night':'day'):ui.appearance;document.body.dataset.appearance=resolved;document.body.classList.toggle('theme-dark',resolved==='night');document.body.classList.toggle('theme-light',resolved!=='night');if($('pv-theme'))$('pv-theme').value=ui.appearance;document.querySelector('meta[name="theme-color"]').content=resolved==='night'?'#0b191c':resolved==='sand'?'#f4efe4':'#f5f4ef';writeStorage('planview-appearance',ui.appearance);}
  function navMarkup(mobile=false){return (mobile?[['explore','Explore','map'],['search','Search','search'],['compare','Compare','layers2'],['cases','Saved','file']]:[['explore','Explore','compass'],['inspect','Inspect','layers'],['compare','Compare','layers2'],['cases','Cases','file']]).map(([view,label,ico])=>`<button type="button" data-view="${view}" class="${view===ui.view?'active':''}" aria-pressed="${view===ui.view}">${mobile?'':icon(ico)}<span>${esc(t(label))}</span>${view==='compare'&&ui.compare.length?`<span class="pv-nav-count">${ui.compare.length}</span>`:''}</button>`).join('');}
  function updateNav(){for(const [id,mobile] of [['pv-nav',false],['pv-mobile-nav',true]]){if(!$(id))continue;$(id).innerHTML=navMarkup(mobile);$(id).querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));}}
  function setView(view){if(view!=='explore'&&ui.measuring)stopMeasure();ui.view=view;document.body.classList.remove('pv-inspecting','pv-searching');$('detail-panel').classList.remove('open');$('sidebar').classList.remove('open');$('pv-workbench').hidden=true;
    if(view!=='search')window.planviewAdvanced?.setOpen?.(false);
    if(view==='inspect'){$('detail-panel').classList.add('open');document.body.classList.add('pv-inspecting');if(!state.selected)renderWelcome();}
    if(view==='search')window.planviewAdvanced?.setOpen?.(true);
    if(view==='compare'||view==='cases'){document.body.classList.add('pv-sidebar-hidden');renderWorkbench(view);}
    else if(innerWidth>1200)document.body.classList.remove('pv-sidebar-hidden');
    updateNav();
  }
  function addShell(){
    const nav=document.createElement('nav');nav.id='pv-nav';nav.className='pv-nav';nav.setAttribute('aria-label','Workspace');nav.dataset.pvManaged='';document.querySelector('.brand').after(nav);
    $('theme-toggle').hidden=true;const theme=document.createElement('select');theme.id='pv-theme';theme.className='pv-theme';theme.dataset.pvManaged='';theme.setAttribute('aria-label',t('Appearance'));theme.innerHTML=['day','night','sand','system'].map(v=>`<option value="${v}">${t(v[0].toUpperCase()+v.slice(1))}</option>`).join('');$('theme-toggle').before(theme);theme.onchange=()=>applyAppearance(theme.value);
    const presets=document.createElement('div');presets.className='pv-presets';presets.id='pv-presets';presets.dataset.pvManaged='';presets.innerHTML=button('Planning','pv-planning')+button('Context','pv-context');document.querySelector('.select-wrap').after(presets);
    $('pv-planning').onclick=()=>preset('planning');$('pv-context').onclick=()=>preset('context');
    const toolbar=document.createElement('div');toolbar.id='pv-toolbar';toolbar.className='pv-toolbar';toolbar.dataset.pvManaged='';toolbar.innerHTML=`<button id="pv-layers" type="button">${icon('layers')}<span>${t('Layers')}</span></button><button id="pv-draw" type="button">${icon('square')}<span>${t('Draw area')}</span></button><button id="pv-measure" type="button">${icon('ruler')}<span>${t('Measure')}</span></button>`;document.querySelector('.map-stage').append(toolbar);
    $('pv-layers').onclick=()=>{if(innerWidth<=600){$('sidebar').classList.toggle('open');$('detail-panel').classList.remove('open');document.body.classList.remove('pv-inspecting');window.planviewAdvanced?.setOpen(false);}else{document.body.classList.toggle('pv-sidebar-hidden');if(innerWidth<=1200&&$('detail-panel').classList.contains('open'))setView('explore');}};
    $('pv-draw').onclick=()=>{$('pv-welcome').hidden=true;stopMeasure();setView('explore');window.planviewAdvanced?.startDrawing(false);};$('pv-measure').onclick=()=>ui.measuring?stopMeasure():startMeasure();
    const welcome=document.createElement('section');welcome.className='pv-welcome';welcome.id='pv-welcome';welcome.dataset.pvManaged='';welcome.innerHTML=`<div class="eyebrow">LIMBURG / 31</div><h2>${t('Your next site starts here.')}</h2><p>${t('Explore adjoining plans, then click a location to inspect its source.')}</p>${button('Explore Maastricht','pv-example','pv-button primary')}`;document.querySelector('.map-stage').append(welcome);$('pv-example').onclick=()=>{selectMunicipality('0935');navigateToPoint(FOCUS,17);selectPoint(FOCUS);};
    const street=document.createElement('section');street.id='pv-street';street.className='pv-street';street.hidden=true;street.dataset.pvManaged='';street.innerHTML=`<div class="pv-aerial" id="pv-aerial" aria-label="Aerial context of selected location"></div><button class="pv-street-close" id="pv-street-close" aria-label="${t('Close')}">×</button><div class="pv-street-copy"><span>${t('Aerial context · Esri')}</span><a id="pv-street-link" target="_blank" rel="noopener noreferrer">${t('Street View')} ${icon('external')}</a><span style="margin-top:5px">${t('Street imagery opens externally')}</span></div>`;document.querySelector('.map-stage').append(street);$('pv-street-close').onclick=()=>{ui.streetClosed=true;street.hidden=true;};
    const workbench=document.createElement('section');workbench.id='pv-workbench';workbench.className='pv-workbench';workbench.dataset.pvManaged='';workbench.hidden=true;workbench.setAttribute('aria-label','Comparison and saved cases');document.querySelector('.workspace').append(workbench);
    const mobile=document.createElement('nav');mobile.id='pv-mobile-nav';mobile.className='pv-mobile-nav';mobile.dataset.pvManaged='';mobile.setAttribute('aria-label','Mobile workspace');document.querySelector('.workspace').append(mobile);
    const zoom=document.createElement('button');zoom.id='pv-zoom-detail';zoom.className='pv-zoom-detail';zoom.dataset.pvManaged='';zoom.textContent=t('Zoom to detail');$('layer-list').after(zoom);zoom.onclick=()=>{const map=state.perspective?state.perspectiveMap:state.map;const p=state.perspective?{lat:map.getCenter().lat,lng:map.getCenter().lng}:map.getCenter();navigateToPoint(p,17);};
    updateNav();
  }
  function preset(name){for(const d of layerDefs)d.on=(name==='planning'?['zoning','double','building','function','area','parcels']:['parcels','novex']).includes(d.id);document.querySelectorAll('[data-layer]').forEach(el=>el.checked=layerDefs.find(d=>d.id===el.dataset.layer).on);updateLayers();for(const d of layerDefs.filter(d=>d.on&&state.selected?.skippedLayers?.includes(d.id)))loadOverlayForSelection(d,state.selected);$('pv-planning').classList.toggle('active',name==='planning');$('pv-context').classList.toggle('active',name==='context');}
  function layerStates(){if(!ui.ready)return;const zoom=state.perspective&&state.perspectiveReady?state.perspectiveMap.getZoom():state.map.getZoom();for(const d of layerDefs){const row=document.querySelector(`[data-layer="${d.id}"]`)?.closest('.layer-row');if(!row)continue;let label=row.querySelector('.pv-layer-state');if(!label){label=document.createElement('small');label.className='pv-layer-state';label.dataset.pvManaged='';row.querySelector('.layer-label').append(label);}const hidden=d.on&&!['zoning','novex'].includes(d.id)&&zoom<12;const k=!d.on?'off':hidden?'zoom':ui.layerStatus[d.id]||'visible';label.dataset.state=k;label.textContent=t({off:'Off',zoom:'Visible closer in',loading:'Loading…',error:'Some tiles unavailable',visible:'Visible'}[k]);}if($('pv-zoom-detail'))$('pv-zoom-detail').hidden=zoom>=16;}
  function relevantFeatures(key,s=state.selected){if(!s?.layers[key])return null;return s.layers[key].filter(f=>{const geo=geoToLatLng(f);return f.properties?.plangebied===s.primary?.properties?.plangebied&&geo&&['Polygon','MultiPolygon'].includes(geo.geometry.type)&&geometryContains(geo.geometry,s.point);});}
  function snapshot(s=state.selected){if(!s)return null;const p=s.point,pr=s.primary?.properties||{},record=s.layers.documents?.find(x=>x.identificatie===pr.plangebied),parcel=s.parcel?.properties||{},envelopes=relevantFeatures('building',s);return {lat:p.lat,lng:p.lng,label:pointLabel(p),designation:pr.naam||t('Not returned'),municipality:s.municipality?.name||'',plan:record?.naam||planTitle(pr.plangebied),sourceId:pr.plangebied||'',sourceUrl:pr.plangebied?officialPlanLink(pr.plangebied,p):OFFICIAL,status:record?.dossierstatus||pr.planstatus||t('Unknown'),date:record?.datum||pr.datum||'',parcel:parcel.perceelnummer?`${parcel.AKRKadastraleGemeenteCodeWaarde||''} ${parcel.sectie||''} ${parcel.perceelnummer}`.trim():t('Not returned'),envelope:envelopes===null?'unknown':envelopes.length?'mapped':'not-returned',features:Object.fromEntries(['double','function','area','dimensions','building'].map(k=>[k,relevantFeatures(k,s)?.map(f=>f.properties?.naam).filter(Boolean)??null])),geometry:pr.plangebied&&s.primary?.geometry?geoToLatLng(s.primary).geometry:null,query:$('advanced-query')?.value||'',capturedAt:new Date().toISOString(),partial:!!s.failed||!!s.loadingLayers,brief:buildCaseBrief()};}
  function decorateDetails(){if(!ui.ready)return;const inner=$('detail-content').querySelector('.detail-inner');if(!inner){const closer=document.createElement('button');closer.className='pv-button';closer.dataset.pvManaged='';closer.textContent=t('Back to map');closer.onclick=()=>setView('explore');$('detail-content').append(closer);return;}
    const sections=[...inner.querySelectorAll(':scope > .detail-section')];sections.forEach((s,i)=>{s.dataset.pvTab=['summary','sources','rules','sources','sources'][i]||'sources';});
    const tabs=document.createElement('div');tabs.className='pv-inspector-tabs';tabs.dataset.pvManaged='';tabs.setAttribute('role','tablist');tabs.innerHTML=['summary','rules','sources'].map(tab=>`<button type="button" role="tab" data-tab="${tab}" aria-selected="${ui.tab===tab}">${t(tab[0].toUpperCase()+tab.slice(1))}</button>`).join('');inner.querySelector('.detail-top').after(tabs);tabs.querySelectorAll('button').forEach(b=>{b.onclick=()=>{ui.tab=b.dataset.tab;applyTab();};b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const all=[...tabs.querySelectorAll('button')],i=all.indexOf(b),next=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;ui.tab=all[next].dataset.tab;applyTab();all[next].focus();};});
    const actions=document.createElement('div');actions.className='pv-inline-actions';actions.dataset.pvManaged='';actions.innerHTML=button('Add to comparison','pv-add-selected')+button('Export brief','pv-export-selected');inner.querySelector('.detail-top').append(actions);$('pv-add-selected').onclick=()=>addCompare(snapshot());$('pv-export-selected').onclick=()=>downloadBrief(snapshot());
    const banner=document.createElement('div');banner.className='pv-evidence-banner'+(state.selected.failed?' warning':'');banner.dataset.pvManaged='';banner.textContent=t(state.selected.failed?'Query failed for some sources.':'Source linked · legal review required');inner.querySelector('.detail-top').append(banner);
    const size=document.createElement('button');size.className='pv-sheet-size';size.dataset.pvManaged='';size.textContent=t($('detail-panel').classList.contains('pv-expanded')?'Collapse details':'Expand details');size.onclick=()=>{$('detail-panel').classList.toggle('pv-expanded');size.textContent=t($('detail-panel').classList.contains('pv-expanded')?'Collapse details':'Expand details');};inner.prepend(size);
    $('close-details').onclick=()=>setView('explore');applyTab();updateStreet();
  }
  function applyTab(){document.querySelectorAll('[data-pv-tab]').forEach(s=>s.hidden=s.dataset.pvTab!==ui.tab);document.querySelectorAll('.pv-inspector-tabs [data-tab]').forEach(b=>(b.setAttribute('aria-selected',String(b.dataset.tab===ui.tab)),b.tabIndex=b.dataset.tab===ui.tab?0:-1));}
  function updateStreet(){const p=state.selected?.point;if(!p)return;keepMobileSelectionVisible();$('pv-welcome').hidden=true;$('pv-street').hidden=ui.streetClosed;$('pv-street-link').href=`https://www.google.com/maps/@?api=1&map_action=pano&viewpoint=${p.lat},${p.lng}`;
    if(innerWidth<=600)return;
    if(!ui.aerial){ui.aerial=L.map('pv-aerial',{zoomControl:false,attributionControl:true,dragging:false,scrollWheelZoom:false,doubleClickZoom:false,boxZoom:false,keyboard:false,touchZoom:false});L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{attribution:'© Esri',maxZoom:19}).addTo(ui.aerial);ui.aerialPin=L.circleMarker([p.lat,p.lng],{radius:5,color:'#fff',weight:2,fillColor:'#087f70',fillOpacity:1}).addTo(ui.aerial);}
    ui.aerial.invalidateSize();ui.aerial.setView([p.lat,p.lng],17,{animate:false});ui.aerialPin.setLatLng([p.lat,p.lng]);
  }
  function keepMobileSelectionVisible(force=false){
    if(innerWidth>600||!state.selected?.point)return;
    const p=state.selected.point,key=`${p.lat}:${p.lng}`;if(!force&&ui.mobilePoint===key)return;ui.mobilePoint=key;clearTimeout(ui.mobilePan);
    ui.mobilePan=setTimeout(()=>{if(innerWidth>600||ui.view!=='inspect'||!state.selected||!samePoint(p,state.selected.point)||$('detail-panel').classList.contains('pv-expanded'))return;
      state.map.panInside([p.lat,p.lng],{paddingTopLeft:[24,90],paddingBottomRight:[24,$('detail-panel').offsetHeight+92],animate:false});
    },750);
  }
  function addCompare(item){if(!item)return;const exists=ui.compare.some(x=>samePoint(x,item));if(exists){setView('compare');return;}if(ui.compare.length>=3){showToast(t('Choose up to three sites.'));setView('compare');return;}ui.compare.push(item);writeStorage('planview-compare-v2',ui.compare);updateNav();showToast(`${ui.compare.length}/3 · ${t('Compare sites')}`);if(ui.view==='compare')renderWorkbench('compare');}
  function resultSnapshot(r){return {lat:r.point.lat,lng:r.point.lng,label:r.name,designation:r.name,municipality:r.municipality,plan:planTitle(r.sourceId),sourceId:r.sourceId,sourceUrl:officialPlanLink(r.sourceId,r.point),status:r.envelopeStatus||r.status,date:r.envelopeDate||'',envelope:r.envelope?'mapped':'unknown',parcel:t('Not queried'),capturedAt:new Date().toISOString(),geometry:geoToLatLng(r.feature)?.geometry,partial:!!r.review,features:{},distances:Object.fromEntries(Object.entries(r.nearFeatures||{}).map(([k,v])=>[k,v?{km:v.km,name:v.item?.name,source:v.item?.source}:null])),industry:r.industry?{km:r.industry.km,name:r.industry.item?.name,source:r.industry.item?.source}:null,query:$('advanced-query').value};}
  function openSnapshot(item){setView('inspect');navigateToPoint(item,17);selectPoint({lat:item.lat,lng:item.lng,address:item.label});}
  function downloadBrief(item){if(!item)return;const lines=item.brief||['PLANVIEW · SITE RESEARCH',item.label,`Designation: ${item.designation}`,`Municipality: ${item.municipality}`,`Plan: ${item.plan}`,`IMRO: ${item.sourceId}`,`Status: ${item.status}`,`Source: ${item.sourceUrl}`].join('\n');download('PlanView-site-brief.txt',`${lines}\n\nEvidence captured: ${item.capturedAt||'Not recorded'}\n${item.partial?'Partial evidence. Reopen this site to refresh.\n':''}Notes / open questions:\n${item.notes||'None recorded'}\n\nResearch support, not a legal buildability decision.\n`,'text/plain');}
  function download(name,body,type){const url=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function renderWorkbench(view){const wb=$('pv-workbench');wb.hidden=false;wb.classList.toggle('compare',view==='compare');wb.innerHTML=`<div class="pv-workbench-head"><div><span class="eyebrow">PLANVIEW / ${view==='compare'?'SHORTLIST':'RESEARCH'}</span><h2>${t(view==='compare'?'Compare sites':'Saved cases')}</h2><p>${t(view==='compare'?'Compare real plan evidence side by side.':'Stored on this device. Sources are snapshots; reopen a site to refresh.')}</p></div><div class="pv-inline-actions">${view==='compare'&&ui.compare.length?button('Export brief','pv-export-comparison'):''}${button('Back to map','pv-workbench-close')}</div></div><div id="pv-workbench-body"></div>`;$('pv-workbench-close').onclick=()=>setView('explore');const box=$('pv-workbench-body');
    if(view==='compare'){
      if(!ui.compare.length){box.innerHTML=`<div class="pv-empty">${icon('layers2')}<h3>${t('No sites compared yet')}</h3><p>${t('Select an area, then add it to your comparison.')}</p></div>`;return;}
      const val=(v)=>esc(v||t('Unknown'));const distance=(x,k)=>x.distances?.[k]?`${x.distances[k].km.toFixed(1)} km<small>${val(x.distances[k].name)} · ${val(x.distances[k].source)}</small>`:t('Not queried');const feature=(x,k)=>x.features?.[k]===null||!x.features?.[k]?t('Not queried'):val(x.features[k].join('; ')||t('Not returned'));
      const rows=[['Designation',x=>val(x.designation)],['Municipality',x=>val(x.municipality)],['Cadastral parcel',x=>val(x.parcel)],['Building envelope',x=>t(x.envelope==='mapped'?'Mapped':x.envelope==='not-returned'?'Not returned':'Not queried')],['Plan status',x=>val(x.status)],['Plan date',x=>val(x.date)],['Heritage / dual',x=>feature(x,'double')],['Dimensions',x=>feature(x,'dimensions')],['Station · approx.',x=>distance(x,'station')],['Park · approx.',x=>distance(x,'park')],['Industry · approx.',x=>x.industry?`${x.industry.km.toFixed(1)} km`:t('Not queried')],['Source',x=>`<a href="${esc(x.sourceUrl)}" target="_blank" rel="noopener noreferrer">${val(x.plan)} ↗</a><small>${val(x.sourceId)}</small>`],['Evidence captured',x=>val(x.capturedAt?new Date(x.capturedAt).toLocaleString():'')],['Review',x=>`${x.partial?t('Partial evidence')+' · ':''}${t('Current legal position must be checked.')}`]];
      box.innerHTML=`<div class="pv-table-wrap"><table class="pv-table"><thead><tr><th>${t('Criterion')}</th>${ui.compare.map((x,i)=>`<th>${String.fromCharCode(65+i)} · ${val(x.label)}<div class="pv-inline-actions"><button class="pv-button" data-open-compare="${i}">${t('Open on map')}</button><button class="pv-button" data-remove-compare="${i}">${t('Remove')}</button></div></th>`).join('')}</tr></thead><tbody>${rows.map(([label,fn])=>`<tr><td>${esc(t(label))}</td>${ui.compare.map(x=>`<td>${fn(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
      box.querySelectorAll('[data-open-compare]').forEach(b=>b.onclick=()=>openSnapshot(ui.compare[Number(b.dataset.openCompare)]));box.querySelectorAll('[data-remove-compare]').forEach(b=>b.onclick=()=>{ui.compare.splice(Number(b.dataset.removeCompare),1);writeStorage('planview-compare-v2',ui.compare);updateNav();renderWorkbench('compare');});$('pv-export-comparison').onclick=()=>download('PlanView-comparison.json',JSON.stringify({version:2,exportedAt:new Date().toISOString(),disclaimer:'Research snapshots. Verify current legal rules.',sites:ui.compare},null,2),'application/json');
    }else{
      if(!state.saved.length){box.innerHTML=`<div class="pv-empty">${icon('file')}<h3>${t('No saved cases yet')}</h3><p>${t('Save a selected location to keep its evidence and your notes on this device.')}</p></div>`;return;}
      box.innerHTML=`<div class="pv-case-grid">${state.saved.map((x,i)=>`<article class="pv-case-card"><span class="eyebrow">${esc(x.municipality||'LIMBURG')}</span><h3>${esc(x.label)}</h3><p>${esc(x.designation||'')} · ${esc(x.plan||'')}</p><p class="pv-small-note">${x.capturedAt?esc(new Date(x.capturedAt).toLocaleString()):t('No evidence snapshot yet')}</p><label for="pv-note-${i}">${t('Notes and open questions')}</label><textarea id="pv-note-${i}" data-note="${i}" maxlength="4000" placeholder="…">${esc(x.notes||'')}</textarea><div class="pv-inline-actions"><button class="pv-button primary" data-case-open="${i}">${t('Open on map')}</button><button class="pv-button" data-case-export="${i}">${t('Export brief')}</button><button class="pv-button" data-case-compare="${i}">${t('Compare')}</button></div></article>`).join('')}</div>`;
      box.querySelectorAll('[data-case-open]').forEach(b=>b.onclick=()=>openSnapshot(state.saved[Number(b.dataset.caseOpen)]));box.querySelectorAll('[data-case-export]').forEach(b=>b.onclick=()=>downloadBrief(state.saved[Number(b.dataset.caseExport)]));box.querySelectorAll('[data-case-compare]').forEach(b=>b.onclick=()=>addCompare(state.saved[Number(b.dataset.caseCompare)]));box.querySelectorAll('[data-note]').forEach(el=>el.oninput=()=>{state.saved[Number(el.dataset.note)].notes=el.value;persistSaved();});
    }
  }
  function startMeasure(){$('pv-welcome').hidden=true;setView('explore');ui.measuring=true;ui.measurePoints=[];window.planviewAdvanced?.cancelDrawing?.();ui.measureLayer?.clearLayers();document.body.classList.add('pv-measuring');$('pv-measure').classList.add('active');$('pv-measure').querySelector('span').textContent=t('Stop measuring');showToast('Click two points on the 2D map to measure distance.');if(state.perspective){togglePerspective();}}
  function stopMeasure(){ui.measuring=false;ui.measurePoints=[];document.body.classList.remove('pv-measuring');ui.measureLayer?.clearLayers();$('pv-measure')?.classList.remove('active');if($('pv-measure'))$('pv-measure').querySelector('span').textContent=t('Measure');}
  function searchExtras(){
    const actions=document.createElement('div');actions.className='pv-search-actions';$('advanced-run').before(actions);actions.append($('advanced-run'));const cancel=document.createElement('button');cancel.type='button';cancel.id='pv-cancel-search';cancel.className='pv-button';cancel.dataset.pvManaged='';cancel.textContent=t('Cancel');cancel.hidden=true;actions.append(cancel);cancel.onclick=()=>window.planviewAdvanced?.cancel?.();
    const tabs=document.createElement('div');tabs.className='pv-result-tabs';tabs.id='pv-result-tabs';tabs.dataset.pvManaged='';tabs.hidden=true;$('advanced-results').before(tabs);
    const manual=document.createElement('details');manual.className='pv-manual';manual.id='pv-manual';manual.dataset.pvManaged='';manual.innerHTML=`<summary>${t('Manual criteria')}</summary><div class="pv-criteria-grid"><label style="grid-column:1/-1">${t('Zoning group')}<select id="pv-group"><option value="">${t('Any designation')}</option><option value="wonen,woongebied">${t('Residential')}</option><option value="gemengd">${t('Mixed use')}</option></select></label><label class="pv-check"><input id="pv-envelope" type="checkbox">${t('Building envelope')}</label><label class="pv-check"><input id="pv-unbuilt" type="checkbox">${t('No mapped building')}</label><label>${t('Near station (km)')}<input id="pv-station" type="number" min="0.1" max="10" step="0.1" placeholder="—"></label><label>${t('Near park (km)')}<input id="pv-park" type="number" min="0.1" max="10" step="0.1" placeholder="—"></label><label style="grid-column:1/-1">${t('Industry distance (km)')}<input id="pv-industry" type="number" min="0.1" max="5" step="0.1" placeholder="—"></label></div><p class="pv-small-note">${t('Blank distance = no filter. Straight-line approximations.')}</p>${button('Run manual search','pv-run-manual','pv-button primary')}`;$('advanced-parsed').before(manual);
    $('pv-run-manual').onclick=()=>{const fields=[$('pv-station'),$('pv-park'),$('pv-industry')];if(fields.some(el=>!el.reportValidity()))return;const groups=$('pv-group').value.split(',').filter(Boolean),station=Number($('pv-station').value),park=Number($('pv-park').value),industry=Number($('pv-industry').value);window.planviewAdvanced?.runManual?.({groups,statuses:[],requireEnvelope:$('pv-envelope').checked,requireUnbuilt:$('pv-unbuilt').checked,nearCamping:false,nearTown:false,nearFeatures:[...(station?['station']:[]),...(park?['park']:[])],avoidIndustry:!!industry,preferQuiet:false,potentialBuildingLand:false,includeReviewLeads:true,unsupported:[],explanation:'Manual criteria. Distances are approximate straight-line screening checks.',distanceKm:{station,park,industry}});};
  }
  function decorateResults(){const advanced=window.planviewAdvanced;if(!advanced)return;const results=advanced.results;const tabs=$('pv-result-tabs');tabs.hidden=!results.length;tabs.innerHTML=[['all','All',results.length],['matches','Matches',results.filter(x=>!x.review).length],['review','Needs review',results.filter(x=>x.review).length]].map(([v,l,n])=>`<button type="button" data-filter="${v}" class="${(advanced.filter||'all')===v?'active':''}">${t(l)} ${n}</button>`).join('');tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>advanced.filterResults?.(b.dataset.filter));
    $('advanced-results').querySelectorAll('[data-smart-result]').forEach(b=>{const index=Number(b.dataset.smartResult),r=results[index];if(!r)return;const add=document.createElement('button');add.className='pv-result-add';add.type='button';add.dataset.pvManaged='';add.textContent=t('Add to comparison');add.onclick=()=>addCompare(resultSnapshot(r));b.after(add);b.onmouseenter=b.onfocus=()=>{ui.hoverLayer?.clearLayers();if(r.feature?.geometry)L.geoJSON(geoToLatLng(r.feature),{interactive:false,style:{color:'#087f70',weight:5,fillOpacity:0}}).addTo(ui.hoverLayer);};b.onmouseleave=b.onblur=()=>ui.hoverLayer?.clearLayers();});
  }
  function translateShell(){
    for(const id of ['pv-presets','pv-toolbar','pv-welcome','pv-manual','pv-street','pv-cancel-search','pv-zoom-detail']){
      const root=$(id);if(!root)continue;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;
      while(node=walker.nextNode()){const text=node.textContent.trim(),key=Object.keys(messages).find(k=>k===text||messages[k].includes(text));if(key)node.textContent=node.textContent.replace(text,t(key));}
    }
  }
  // Hooks keep data ownership in app.js. They are installed before its load handler runs.
  const originalRender=renderDetails;renderDetails=function(){const whyOpen=$('why-button')?.getAttribute('aria-expanded')==='true';originalRender();decorateDetails();if(whyOpen&&$('why-content')){$('why-content').hidden=false;$('why-button').setAttribute('aria-expanded','true');}};
  const originalLayers=updateLayers;updateLayers=function(){originalLayers();layerStates();};
  const originalSelect=selectPoint;selectPoint=async function(p){if(ui.measuring)return;if(ui.ready){ui.tab='summary';ui.streetClosed=false;setView('inspect');$('pv-welcome').hidden=true;$('pv-street').hidden=true;}return originalSelect(p);};
  const originalSave=saveCurrent;saveCurrent=function(){originalSave();const snap=snapshot();if(!snap)return;const record=state.saved.find(x=>samePoint(x,snap));if(record){const notes=record.notes||'';Object.assign(record,snap,{notes});persistSaved();}if(ui.view==='cases')renderWorkbench('cases');};
  const originalRegion=loadRegion;loadRegion=async function(){await originalRegion();if(!state.selectedPoint){selectMunicipality('0935');navigateToPoint(FOCUS,16);}layerStates();};
  window.addEventListener('load',()=>{
    ui.compare=readStorage('planview-compare-v2',[]).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lng)).slice(0,3);addShell();ui.ready=true;applyAppearance(readStorage('planview-appearance','day'));matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(ui.appearance==='system')applyAppearance('system');});
    ui.measureLayer=L.layerGroup().addTo(state.map);ui.hoverLayer=L.layerGroup().addTo(state.map);
    state.map.on('click',e=>{if(!ui.measuring)return;if(ui.measurePoints.length===2){ui.measureLayer.clearLayers();ui.measurePoints=[];}ui.measurePoints.push(e.latlng);L.circleMarker(e.latlng,{radius:5,color:'#087f70',fillColor:'#fff',fillOpacity:1}).addTo(ui.measureLayer);if(ui.measurePoints.length===2){const distance=state.map.distance(...ui.measurePoints);L.polyline(ui.measurePoints,{color:'#087f70',weight:3,dashArray:'5 5'}).bindTooltip(distance>=1000?`${(distance/1000).toFixed(2)} km`:`${distance.toFixed(0)} m`,{permanent:true,className:'pv-measure-value'}).addTo(ui.measureLayer);}});
    for(const [id,layer] of Object.entries(state.planLayers)){layer.on('loading',()=>{ui.layerStatus[id]='loading';layerStates();});layer.on('load',()=>{if(ui.layerStatus[id]!=='error')ui.layerStatus[id]='visible';layerStates();});layer.on('tileerror',()=>{ui.layerStatus[id]='error';layerStates();});}state.map.on('zoomend',layerStates);
    window.addEventListener('resize',()=>keepMobileSelectionVisible(true));searchExtras();layerStates();document.querySelector('.map-hint').style.display='none';
    window.addEventListener('planview-search-open',e=>{document.body.classList.toggle('pv-searching',e.detail.open);if(e.detail.open){stopMeasure();ui.view='search';$('pv-workbench').hidden=true;$('detail-panel').classList.remove('open');document.body.classList.remove('pv-inspecting');$('sidebar').classList.remove('open');}else if(ui.view==='search')ui.view='explore';updateNav();});
    window.addEventListener('planview-search-results',decorateResults);
    window.addEventListener('planview-search-busy',e=>{$('pv-cancel-search').hidden=!e.detail.busy;$('pv-run-manual').disabled=e.detail.busy;});
    document.addEventListener('keydown',e=>{if(e.key==='Escape'){stopMeasure();setView('explore');}});
    window.addEventListener('planview-language-change',()=>{translateShell();updateNav();layerStates();$('pv-theme').innerHTML=['day','night','sand','system'].map(v=>`<option value="${v}">${t(v[0].toUpperCase()+v.slice(1))}</option>`).join('');$('pv-theme').value=ui.appearance;if(state.selected)renderDetails();if(['cases','compare'].includes(ui.view))renderWorkbench(ui.view);});
  });
})();
